{% set name = "ngspice" %}
{% set version = "32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ayera.dl.sourceforge.net/project/ngspice/ng-spice-rework/{{ version }}/ngspice-{{ version }}.tar.gz
  sha256: 3cd90c4e94516d87c5b4d02a3a6405b1136b25d05c871d4fee1fd7c4c0d03ef2

  patches:
   - patches/libtoolize-name.patch  # [osx]
   - patches/vngspice-install-location.patch  # [win]

build:
  number: 3
  skip: True  # [win and vc<14]

# Due to how 'conda render' extracts metadata info, the 'outputs'
# key must appear OUTSIDE of the jinja conditional below!
outputs:

##
## UNIX
##
{% if unix %}

  - name: ngspice-lib
    script: build_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - autoconf
        - automake
        - libtool
        - texinfo
        - bison
        - flex

      host:
        - ncurses
        - readline

      run:
        - ncurses
        - readline

    test:
      commands:
        - test -f $PREFIX/lib/libngspice{{ SHLIB_EXT }}

  - name: ngspice-exe
    script: build_exe.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - autoconf
        - automake
        - libtool
        - texinfo
        - bison
        - flex

      host:
        - ncurses
        - readline
        - xorg-libx11
        - xorg-libxaw
        - xorg-libxt

      run:
        - ncurses
        - readline
        - xorg-libx11
        - xorg-libxaw
        - xorg-libxt

    test:
      commands:
        - $PREFIX/bin/ngspice --version

  - name: ngspice
    requirements:
      run:
        - {{ pin_subpackage('ngspice-lib', max_pin="x.x.x.x") }}
        - {{ pin_subpackage('ngspice-exe', max_pin="x.x.x.x") }}

    test:
      commands:
        - test -f $PREFIX/lib/libngspice{{ SHLIB_EXT }}
        - $PREFIX/bin/ngspice --version

##
## WINDOWS
##
{% else %}

  - name: ngspice-lib
    script: build_lib.bat

    requirements:
      build:
        - {{ compiler('c') }}
        - winflexbison

    test:
      commands:
        - if not exist %PREFIX%\\bin\\ngspice.dll exit 1

  - name: ngspice-exe
    script: build_exe.bat

    requirements:
      build:
        - {{ compiler('c') }}
        - winflexbison

    test:
      commands:
        - "%PREFIX%\\bin\\ngspice_con.exe --version"

  - name: ngspice
    requirements:
      run:
        - {{ pin_subpackage('ngspice-lib', max_pin="x.x.x.x") }}
        - {{ pin_subpackage('ngspice-exe', max_pin="x.x.x.x") }}

    test:
      commands:
        - if not exist %PREFIX%\\bin\\ngspice.dll exit 1
        - "%PREFIX%\\bin\\ngspice_con.exe --version"

{% endif %}

about:
  home: http://ngspice.sourceforge.net
  doc_url: http://ngspice.sourceforge.net/docs.html
  dev_url: http://ngspice.sourceforge.net/devel.html

  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING

  summary: 'The open source spice simulator for electric and electronic circuits'
  description: |
    ngspice is the open source spice simulator for electric and electronic circuits.
    
    Such a circuit may comprise of JFETs, bipolar and MOS transistors, passive elements
    like R, L, or C, diodes, transmission lines and other devices, all interconnected
    in a netlist. Digital circuits are simulated as well, event driven and fast, from
    single gates to complex circuits. And you may enter the combination of both analog
    and digital as a mixed-signal circuit.
    
    ngspice offers a wealth of device models for active, passive, analog, and digital
    elements. Model parameters are provided by the semiconductor manufacturers.
    The user add her circuits as a netlist, and the output is one or more graphs of
    currents, voltages and other electrical quantities or is saved in a data file.

    Note:
      This build was configured with `--enable-xspice --enable-cider --enable=openmp`
      See the [build script](https://git.io/JfVZX) for more specifics.

extra:
  recipe-maintainers:
    - stuarteberg
